AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  ImageResizer:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: image-resizer.handler
      Runtime: nodejs8.10
      Policies: AmazonS3FullAccess
      Timeout: 20
      MemorySize: 1024
  ImageResizerInvokePermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref ImageResizer
      Principal: sns.amazonaws.com

  ImageAnalyzer:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: image-analyzer.handler
      Runtime: nodejs8.10
      MemorySize: 512
      Policies: 
          - AmazonS3FullAccess
          - AmazonRekognitionFullAccess
          - AmazonDynamoDBFullAccess
      Timeout: 20
  ImageAnalyzerInvokePermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref ImageAnalyzer
      Principal: sns.amazonaws.com

  SnsTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      TopicName: 'image-analyzer-topic'
      Subscription:
        - Protocol: lambda
          Endpoint: !GetAtt ImageResizer.Arn
        - Protocol: lambda
          Endpoint: !GetAtt ImageAnalyzer.Arn
  SNSTopicPolicy:
    Type: 'AWS::SNS::TopicPolicy'
    Properties:
      Topics:
        - !Ref SnsTopic
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: 'sns:Publish'
            Resource: !Ref SnsTopic
            Condition:
              ArnLike:
                aws:SourceArn: !Sub "arn:aws:s3:::henrikrekognition"
            Principal:
              AWS: '*'

  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "henrikrekognition"
      NotificationConfiguration:
        TopicConfigurations:
          - Topic: !Ref SnsTopic
            Event: 's3:ObjectCreated:*'
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: 'images/'

  ImageLabels:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: image-labels
      AttributeDefinitions:
        - AttributeName: image
          AttributeType: S
      KeySchema:
        - AttributeName: image
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

